### ISSUE TITLE
Is it possible to use the library without expo?

### ISSUE THREAD

**Issue by ahmetbicer** [alantoa/universal-tooltip#10]
I am trying to use the library in a bare react native project,  installed the library with `yarn add universal-tooltip@next` and run a `pod install`. When i try to use the library it throws an error like the screenshot below. Is it possible to use the library without expo or do i need to install [expo-modules](https://docs.expo.dev/bare/installing-expo-modules/) to my project? Thanks

   <img src="https://github.com/alantoa/universal-tooltip/assets/45371442/9e1a6e1f-89dc-4a3b-a5d2-1fc7178b9675" width="350">

**Comment by alantoa** [comment]
hey, nope, you have to install expo-modules on your project before you can use it, I don't think it will affect your project anyway!

**Comment by ahmetbicer** [comment]
Ok, thanks a lot!
