### ISSUE TITLE
Android UI issue

### ISSUE THREAD

**Issue by AdzeB** [alantoa/universal-tooltip#11]
I have this issue with the tooltip that it doesn't show anything but on the IOS simulator it looks exactly how I want it

IOS:
![image](https://github.com/alantoa/universal-tooltip/assets/59929333/a7837263-caa0-46c7-bd36-058b3a17dde3)

Android:
<img width="181" alt="image" src="https://github.com/alantoa/universal-tooltip/assets/59929333/106cae47-155b-4d94-b46c-eff08920ffcf">

The Tooltip.Content I use:
`  
<Tooltip.Content
                sideOffset={3}
                containerStyle={{
                  paddingLeft: 8,
                  paddingRight: 8,
                  paddingTop: 8,
                  paddingBottom: 8,
                }}
                onTap={() => {
                  setOpen(false);
                }}
                dismissDuration={500}
                disableTapToDismiss
                side="top"
                presetAnimation="fadeIn"
                backgroundColor="#ffffff"
              >
                <View
                  style={{
                    backgroundColor: "#ffffff",
                    width: 130,
                    height: toolTipContent.length * 34,
                    borderRadius: 10,
                    shadowColor: "#000",
                    shadowOffset: { width: 0, height: 2 },
                    shadowOpacity: 0.2,
                    shadowRadius: 4,
                    elevation: 3,
                  }}
                >
                  {toolTipContent.map((itemData) => (
                    <View
                      style={{
                        flexDirection: "row",
                        alignItems: "center",
                        paddingVertical: 8, // space between each item vertically
                        borderBottomWidth:
                          toolTipContent.indexOf(itemData) !==
                          toolTipContent.length - 1
                            ? 0.5
                            : 0, // bottom border for separation except for the last item
                        borderColor: "#eee",
                        paddingHorizontal: 8,
                      }}
                      key={itemData.id}
                    >
                      <View
                        style={{
                          height: 8,
                          borderRadius: 4,
                          backgroundColor: COLORS.primaryBlue,
                          marginRight: 8,
                          width: 8,
                        }}
                      />
                      <Text>{itemData.text}</Text>
                    </View>
                  ))}
                </View>
              </Tooltip.Content>
`

**Comment by alantoa** [comment]
Hey @AdzeB  I can't reproduce it. Can you provide an example code on Snack? Or create a reproducible example project? I would be happy to check it out!
