### ISSUE TITLE
Lack of types, Can't get auto completion.

### ISSUE THREAD

**Issue by mrpmohiburrahman** [alantoa/universal-tooltip#16]
Hi @alantoa , I am trying to use this library in my project, but I am not getting autocompletion suggestions.
Does this library has proper types set up?

**Comment by alantoa** [comment]
hey @mrpmohiburrahman , yes for sure, you can see [here](https://github.com/alantoa/universal-tooltip/blob/main/src/universal-tooltip.types.ts) where I set the types.
