### ISSUE TITLE
Don't automatically choose between popover / tooltip

### ISSUE THREAD

**Issue by nandorojo** [alantoa/universal-tooltip#3]
The current implementation breaks SSR hydration since it conditionally toggles tooltip vs popover based on the web device. Instead, it should be a flag to prevent hydration mismatches. This would also let users wrap buttons with tooltips without interrupting touches on mobile browsers. I think it could be a prop.

**Comment by alantoa** [comment]
yeah, that makes sense, I also don't want to use automatically choose between Popover / Tooltip.
I thought of just using the one of Tooltip components to toggle it on mobile, but I feel it's a little bit hack.
I have [created an example](https://codesandbox.io/s/hungry-tdd-mhtf3r) on the mobile web before, do you mean something just like this?

**Comment by nandorojo** [comment]
I think one good solution could be to pass `popover` as a prop for it to use on mobile Web

**Comment by nandorojo** [comment]
If that prop is true, maybe it renders differently after a render in a layout effect…

**Comment by alantoa** [comment]
yeah, that's a good solution for now! I'll go to try it.
