### ISSUE TITLE
ios

### ISSUE THREAD

**Issue by nandorojo** [alantoa/universal-tooltip#8]
great work here! looks like the ios library isn't maintained anymore. any thoughts on changing it?

**Comment by alantoa** [comment]
I'm trying to use [Popovers](https://github.com/aheze/Popovers) to instead, it can be closed when scrolled, and much much better! 
But now I still have a custom view issue, and I'm trying to fix it.

**Comment by alantoa** [comment]
Just did that. If you want, feel free to try this [universal-tooltip@next](https://github.com/alantoa/universal-tooltip/releases/tag/1.0.0-2) version!

**Comment by nandorojo** [comment]
wow, awesome! does tapping outside close it too, or just scrolling?

**Comment by nandorojo** [comment]
looks like it does from what i see. amazing

**Comment by alantoa** [comment]
Yes, both clicking outside and scrolling support closing!
